import './globals.css'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";

// components



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mango Creative',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <Navbar /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
